apiVersion: v1
kind: ConfigMap
metadata:
  name: nostos-config
  namespace: default
data:
  KAFKA_BROKERS: kafka-broker-0.kafka-headless:9092,kafka-broker-1.kafka-headless:9092,kafka-broker-2.kafka-headless:9092
  KAFKA_TOPIC: ingress-topic
  SERVER_ADDR: ":8080"
