apiVersion: v1
kind: ServiceAccount
metadata:
  name: nostos
  namespace: default
  labels:
    app: nostos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nostos
  namespace: default
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nostos
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nostos
subjects:
  - kind: ServiceAccount
    name: nostos
    namespace: default
