apiVersion: v1
kind: Service
metadata:
  name: nostos-ingress
  namespace: default
  labels:
    app: nostos
    component: ingress
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nostos
    component: ingress
---
apiVersion: v1
kind: Service
metadata:
  name: nostos-ingress-lb
  namespace: default
  labels:
    app: nostos
    component: ingress
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nostos
    component: ingress
